### ISSUE TITLE
Subscription to sensors freeze after some time (android)

### ISSUE THREAD

**Issue by Janchu** [tugberka/react-native-mds#1]
Subscription to any sensor (Acc/Gyro/Magn/Imu6/Imu9) freezes after some time. This time varies between tens of seconds to some minutes. The connection to the Movesense device is not lost and simply resubscribing resolves the issue. This happens with all sample rates.

The Movesense device used is on the latest firmware (1.9) and I'm using the latest mdslib (mdslib-1.34.1(1)-release.aar [2019-05-15]). React Native version used is 0.59.8.

The Android devices I have used for testing are Nokia 8 Scirocco (android 9.0.0) and OnePlus 3T (android 8.0.0). The issue exists on both devices.

I haven't had the chance to test this on iOS devices so I'm not sure if this is Android specific or not.

Is this an issue with react-native-mds, mdslib, or android? Could this be caused by some android power saving feature? The freezing happens even when the phone screen is kept on though.

**Comment by tugberka** [comment]
Could you maybe put here logs when you reproduce the issue? Have you also tried with the Movesense example apps (like showcase app on the official repo)? Is the issue reproducible with that app using the same phone & sensors? I could not reproduce it myself using the same versions of sensor firmware and mds. (react-native v0.59.9 and Android 9 phone)

**Comment by Reiss-Cashmore** [comment]
I am currently building Cordova libraries for movesense based heavily on your implementation here (Which I think is very good and am very appreciative that you took the time to make it) and can confirm that after about 30-40 seconds that it does drop the subscription. Forcing the need to resubscribe

Check out the cordova plugin project here (Please be kind it is a WIP and very much prototype stage currently): https://github.com/Reiss-Cashmore/cordova-plugin-movesense

Here are some debug logs from my app which shows the movesense internal libraries consciously deleting the subscription after I have subscribed to the /HR data and am receiving data successfully

I am wondering are there any parameters we should pass to the mds.subscribe method within the contract object or somewhere else to make the mds library not drop the subscription?

```
"I/System.out: {"Body": {"average": 91.800003051757812, "rrData": [632]}, "Uri": "192830000514/Meas/HR", "Method": "PUT"}
D/BleManager: Received data: WB_DATAMSG_CLIENT_ON_NOTIFY, type: 1, direct msg, msgLen: 25, reqId: 0, size: 31
D/MdsOperationHandler: SDSInternalCallback with call type: 2 header: {"Content-Type": "application/json", "Uri": "MDS/EventListener/42", "Content-Length": 106, "Reason": "CUSTOM_STATUS", "Status": 0}
I/Suunto Subscribe Notification: {"Body": {"average": 92.400001525878906, "rrData": [640]}, "Uri": "192830000514/Meas/HR", "Method": "PUT"}
I/System.out: {"Body": {"average": 92.400001525878906, "rrData": [640]}, "Uri": "192830000514/Meas/HR", "Method": "PUT"}
D/BleManager: Received data: WB_DATAMSG_CLIENT_ON_NOTIFY, type: 1, direct msg, msgLen: 25, reqId: 0, size: 31
D/MdsOperationHandler: SDSInternalCallback with call type: 2 header: {"Content-Type": "application/json", "Uri": "MDS/EventListener/42", "Content-Length": 106, "Reason": "CUSTOM_STATUS", "Status": 0}
I/Suunto Subscribe Notification: {"Body": {"average": 92.800003051757812, "rrData": [640]}, "Uri": "192830000514/Meas/HR", "Method": "PUT"}
I/System.out: {"Body": {"average": 92.800003051757812, "rrData": [640]}, "Uri": "192830000514/Meas/HR", "Method": "PUT"}
I/Komposti: [SDS REQUEST] type: DEL uri: suunto://MDS/EventListener/42
D/BleManager: sendCb(10000001), 13 bytes
D/BleManager: Send complete
D/BleManager: Received data: WB_DATAMSG_CLIENT_ON_UNSUBSCRIBE_RESULT, type: 9, direct msg, msgLen: 10, reqId: 28672, size: 16
I/Komposti: [SDS RESPONSE] type: DEL status: OK header: {"TaskId": 43, "Uri": "suunto://MDS/EventListener/42", "Content-Length": 0, "Reason": "OK", "Status": 200}
D/MdsOperationHandler: SDSInternalCallback with call type: 4 header: {"TaskId": 43, "Uri": "suunto://MDS/EventListener/42", "Content-Length": 0, "Reason": "OK", "Status": 200}"
```
I am really not a huge fan of the way movesense have gone about providing documentation. The sample projects in bitbucket are way too unclear and nested, plus not easily searchable. There is much room for improvement

If there are any suggestions you might have based on your experience using the mds library I would very much appreciate your thoughts

**Comment by Reiss-Cashmore** [comment]
It's okay I found the solution to my issue. The internal mds library does not store strong references to subscriptions so automatically collects the garbage so to speak, of subscriptions with only weak references. 

This issue on bitbucket shows the solution: https://bitbucket.org/suunto/movesense-mobile-lib/issues/45/android-random-unsubscribe-events
